using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

public class CKF_Path : MonoBehaviour
{
    public CKF_PathController controller;
    public Transform nodeA, nodeB;
    public bool enterA, enterB;
    public bool enteredA, enteredB; //removed Readonlyfield to enable split path
    [ReadonlyField] public bool completed;
    [Min(0)]public float pathMultA = 1, pathMultB = 1;
    [ReadonlyField] public float dist, distA, distB; // if distA + distB >= dist then disable
    [ReadonlyField] public CKF_PathSprite pathA, pathB;
    [Min(0)] public float pathWidth;
    [Color4Field] public Color pathInnerColor, pathOuterColor;
    [ReadonlyField] public Transform glowA, glowB;

    private readonly HashSet<int> InteractActorInA = new(), InteractActorInB = new();
    private readonly List<float> interactValueA = new(), interactValueB = new();
    private readonly List<CKF_PathInteractActor> interactA = new(), interactB = new();
    private int interactedIndexA = 0, interactedIndexB = 0;

    public void Awake()
    {
        if (nodeA == null || nodeB == null) return;
        dist = Vector3.Distance(nodeA.position, nodeB.position);
        if (controller != null) controller.AddPath(this);
    }
    public void SetNode(Transform a, Transform b)
    {
        nodeA = a;
        nodeB = b;
        dist = Vector3.Distance(nodeA.position, nodeB.position);
    }
    public void SetController(CKF_PathController c)
    {
        if (controller != null) controller.RemovePath(this);
        controller = c;
        if (controller != null) controller.AddPath(this);
    }

    private void UpdateDistA()
    {
        while (interactedIndexA != interactValueA.Count && interactValueA[interactedIndexA] <= distA)
            interactA[interactedIndexA++].Interact();
    }

    private void UpdateDistB()
    {
        while (interactedIndexB != interactValueB.Count && interactValueB[interactedIndexB] <= distB)
            interactB[interactedIndexB++].Interact();
    }

    public void SetEnteredA(bool value) { enteredA = value; }
    public void SetEnteredB(bool value) { enteredB = value; }

    public void Enter(Transform node, float amount)
    {   // known issue: if multiple are called on the same frame, it won't choose the greater amount
        // fix: CKF_PathController could lookup connecting CKF_Path(s) to determine if others would lead to greater amount
        // fix: CKF_Path could store the time of enter and if another enter occured at the same time then it would compare the amount
        // fix: by "time" it could be generated by CKF_PathController at UpdatePaths by counting the number of executions as it is what leads the Enter
        if (completed || (node == nodeA && (!enterA || enteredA)) || (node == nodeB && (!enterB || enteredB))) return;
        if (node == nodeA)
        {
            enteredA = true;
            distA = amount * pathMultA; // distA should be 0
            UpdateDistA();
            glowA = Instantiate(controller.glowSprite, controller.glowLayer).GetComponent<RectTransform>();
            glowA.position = Vector3.Lerp(nodeA.position, nodeB.position, Mathf.Min(distA / dist, 1));
            if (controller.cameraBounds != null)
                controller.cameraBounds.CapturePoint(glowA.position);
            pathA = Instantiate(controller.pathSprite, controller.transform).GetComponent<CKF_PathSprite>();
            pathA.nodeA = node;
            pathA.nodeB = glowA;
            pathA.endPointRadius = pathWidth;
            pathA.SetWidth(pathWidth);
            pathA.SetInnerColor(pathInnerColor);
            pathA.SetOuterColor(pathOuterColor);

            if (!enteredB && distA >= dist)
            {
                enteredB = true;
                controller.ExploreNode(nodeB, pathMultA == 1 ? distA - dist : (distA - dist) / pathMultA);
            }
            controller.AddActive(this);
        }
        else // node == nodeB mest be true
        {
            enteredB = true;
            distB = amount * pathMultB; // distB should be 0
            UpdateDistB();
            glowB = Instantiate(controller.glowSprite, controller.glowLayer).transform;
            glowB.position = Vector3.Lerp(nodeB.position, nodeA.position, Mathf.Min(distB / dist,1));
            if(controller.cameraBounds != null)
                controller.cameraBounds.CapturePoint(glowB.position);
            pathB = Instantiate(controller.pathSprite, controller.transform).GetComponent<CKF_PathSprite>();
            pathB.nodeA = node;
            pathB.nodeB = glowB;
            pathB.endPointRadius = pathWidth;
            pathB.SetWidth(pathWidth);
            pathB.SetInnerColor(pathInnerColor);
            pathB.SetOuterColor(pathOuterColor);

            if (!enteredA && distB >= dist)
            {
                enteredA = true;
                controller.ExploreNode(nodeA, pathMultB == 1 ? distB - dist : (distB - dist) / pathMultB);
            }
            controller.AddActive(this);
        }

        if ((distA + distB) >= dist)
            Completed();
    }

    public void Add(float amount)
    {
        if (completed) return;
        bool init_enteredB = enteredB;

        if (enteredA)
        {
            distA += amount * pathMultA;
            UpdateDistA();
            glowA.position = Vector3.Lerp(nodeA.position, nodeB.position, Mathf.Min(distA / dist, 1));
            if (controller.cameraBounds != null)
                controller.cameraBounds.CapturePoint(glowA.position);
            if (!enteredB && distA >= dist)
            {
                enteredB = true;
                controller.ExploreNode(nodeB, pathMultA == 1 ? distA - dist : (distA - dist) / pathMultA);
            }
        }

        if (init_enteredB)
        {
            distB += amount * pathMultB;
            UpdateDistB();
            glowB.position = Vector3.Lerp(nodeB.position, nodeA.position, Mathf.Min(distB / dist, 1));
            if (controller.cameraBounds != null)
                controller.cameraBounds.CapturePoint(glowB.position);
            if (!enteredA && distB >= dist)
            {
                enteredA = true;
                controller.ExploreNode(nodeA, pathMultB == 1 ? distB - dist : (distB - dist) / pathMultB);
            }
        }

        if ((distA + distB) >= dist)
            Completed();
    }

    private void Completed()
    {
        if (completed) return;
        completed = true;
        // disable glow // call CKF_Timer
        controller.RemoveActive(this);

        if (pathA != null && pathB != null)
        {
            Destroy(pathB.gameObject);
        }
        if (pathA == null)
        {
            pathA = pathB;
        }
        pathB = null;

        pathA.nodeA = nodeA;
        pathA.nodeB = nodeB;
        if (glowA != null)
        {
            Destroy(glowA.gameObject);
            glowA = null;
        }
        if (glowB != null)
        {
            Destroy(glowB.gameObject);
            glowB = null;
        }
    }

    public void AddInteractActor(CKF_PathInteractActor pia)
    {
        Fn.SphereIntersectLine(nodeA.position,nodeB.position, pia.transform.position,pia.distance, out float lerpA, out float lerpB);

        int id = pia.GetInstanceID();
        if (InteractActorInA.Remove(id))
        {
            
            for(int i = interactA.Count; --i > -1;)
            {
                if (interactA[i].GetInstanceID() != id) continue;
                interactA.RemoveAt(i);
                break;
            }
        }
        if (0 <= lerpA && lerpA <= 1)
        {
            float lerpDist = dist * lerpA;
            int index = Fn.BinaryInsertIndex(interactValueA, lerpDist);
            interactValueA.Insert(index, lerpDist);
            interactA.Insert(index, pia);
            InteractActorInA.Add(id);
        }
        if (InteractActorInB.Remove(id))
        {

            for (int i = interactB.Count; --i > -1;)
            {
                if (interactB[i].GetInstanceID() != id) continue;
                interactB.RemoveAt(i);
                break;
            }
        }
        if (0 <= lerpB && lerpB <= 1)
        {
            float lerpDist = dist * lerpB;
            int index = Fn.BinaryInsertIndex(interactValueB, lerpDist);
            interactValueB.Insert(index, lerpDist);
            interactB.Insert(index, pia);
            InteractActorInB.Add(id);
        }
    }

    public void PathReset()
    {
        controller.RemoveActive(this);

        if (pathA != null) { Destroy(pathA); pathA = null; }
        if (pathB != null) { Destroy(pathB); pathB = null; }
        if (glowA != null) { Destroy(glowA.gameObject); glowA = null; }
        if (glowB != null) { Destroy(glowB.gameObject); glowB = null; }

        distA = 0; distB = 0; interactedIndexA = 0; interactedIndexB = 0;
        enteredA = false; enteredB = false;
        completed = false;
    }

    private void OnDrawGizmos()
    {
        if (nodeA == null || nodeB == null) return;
        Draw(nodeA.position, nodeB.position, transform.forward, pathWidth, enterA, enterB);
        /*Vector3 cross = Vector3.Cross((nodeA.position - nodeB.position).normalized, transform.forward), widthCross = pathWidth * cross;
        float distance = Vector3.Distance(nodeA.position, nodeB.position), radius = 0.125f * distance;

        Gizmos.color = Color.magenta;
        Gizmos.DrawLine(nodeA.position + widthCross, nodeB.position + widthCross);
        Gizmos.DrawLine(nodeA.position - widthCross, nodeB.position - widthCross);

        Gizmos.color = Color.blue;
        Gizmos.DrawWireSphere(nodeA.position, radius);
        Gizmos.DrawWireSphere(nodeB.position, radius);
        Gizmos.color = Color.green;
        if (enterA)
        {
            Vector3 near = Vector3.Lerp(nodeA.position, nodeB.position, 0.33f),
                nearnear = Vector3.Lerp(nodeA.position, nodeB.position, 0.23f),
            shortCross = 0.1f * distance * cross;
            Gizmos.DrawLine(nearnear - shortCross, near);
            Gizmos.DrawLine(nearnear + shortCross, near);
        }
        if (enterB)
        {
            Vector3 near = Vector3.Lerp(nodeA.position, nodeB.position, 0.67f),
                nearnear = Vector3.Lerp(nodeA.position, nodeB.position, 0.77f),
            shortCross = 0.1f * distance * cross;
            Gizmos.DrawLine(nearnear - shortCross, near);
            Gizmos.DrawLine(nearnear + shortCross, near);
        }*/
    }

    public static void Draw(Vector3 positionA, Vector3 positionB, Vector3 forward, float pathWidth, bool enterA, bool enterB)
    {
        Vector3 cross = Vector3.Cross((positionA - positionB).normalized, forward), widthCross = pathWidth * cross;
        float distance = Vector3.Distance(positionA, positionB), radius = 0.125f * distance;

        Gizmos.color = Color.magenta;
        Gizmos.DrawLine(positionA + widthCross, positionB + widthCross);
        Gizmos.DrawLine(positionA - widthCross, positionB - widthCross);

        Gizmos.color = Color.blue;
        Gizmos.DrawWireSphere(positionA, radius);
        Gizmos.DrawWireSphere(positionB, radius);
        Gizmos.color = Color.green;
        if (enterA)
        {
            Vector3 near = Vector3.Lerp(positionA, positionB, 0.33f),
                nearnear = Vector3.Lerp(positionA, positionB, 0.23f),
            shortCross = 0.1f * distance * cross;
            Gizmos.DrawLine(nearnear - shortCross, near);
            Gizmos.DrawLine(nearnear + shortCross, near);
        }
        if (enterB)
        {
            Vector3 near = Vector3.Lerp(positionA, positionB, 0.67f),
                nearnear = Vector3.Lerp(positionA, positionB, 0.77f),
            shortCross = 0.1f * distance * cross;
            Gizmos.DrawLine(nearnear - shortCross, near);
            Gizmos.DrawLine(nearnear + shortCross, near);
        }
    }
}
